### ISSUE TITLE
Beim Craften 2 mal das gleiche Item hintereinander

### ISSUE THREAD

**Issue by Naaaaaam** [HGLabor/speedrun-v2#5]
Man kann bei der Crafting Disziplin 2 mal das gleiche Item hintereinander bekommen, was relativ dumm ist, da man es davor schon hatte und es somit nur nervig ist. Dazu kann es passieren, das neue Leute denken, dass das Absicht ist und somit die Lust verlieren auf diesen Modus.

(Das hatte ich auch schon auf dem Discord geschrieben)

**Comment by Krxwallo** [comment]
Gefixed in https://github.com/HGLabor/speedrun-v2/commit/f35469ae8fda0abcb374c1c10c4140e1aee2eac3
