### ISSUE TITLE
obsi turm

### ISSUE THREAD

**Issue by Wurliiii** [HGLabor/speedrun-v2#7]
wenn man bei dem crystal ding ein tower abschießt dann ist er nicht bis ganz nach  unten aus emeralds ich weiß juckt aber 
![image](https://user-images.githubusercontent.com/84781412/123952253-08c72700-d9a6-11eb-956d-4ed83369766a.png)

**Comment by Krxwallo** [comment]
Bis welche Höhe sieht man die max

**Comment by Wurliiii** [comment]
An dem Turm? Also bei dem siehst du das rechtsbda sind coords

**Comment by Krxwallo** [comment]
Wtf ich weiß wie man coords sieht ich mein weißt du zufällig wie weit runter ich dass einstellen soll

**Comment by Krxwallo** [comment]
Fixed in https://github.com/HGLabor/speedrun-v2/commit/bbe51720efe11fdeacd78074920a42b7005c16db
